stages:
  load_data:
    cmd: python src/load_save_data.py --config=params.yaml
    deps:
    - src/get_data.py
    - src/load_save_data.py
    - data_given/tips.csv
    outs:
    - data/raw/tips.csv

  split_data:
    cmd: python src/split_data.py --config=params.yaml
    deps:
    - src/split_data.py
    - data/raw/tips.csv

    outs:
    - data/processed/train_tips.csv
    - data/processed/test_tips.csv
  train-evaluate:
    cmd: python src/train_evaluate.py --config=params.yaml
    deps:
    - data/processed/train_tips.csv
    - data/processed/test_tips.csv
    - src/train_evaluate.py
    params:
    - estimators.ElasticNet.params.alpha
    - estimators.ElasticNet.params.l1_ratio
    metrics:
    - reports/scores.json:
        cache: False
    - reports/params.json:
        cache: False
    outs:
    - saved_models/model.joblib


