stages:
  load_data:
    cmd: python src/load_save_data.py --config=params.yaml
    deps:
    - src/get_data.py
    - src/load_save_data.py
    - data_given/tips.csv
    outs:
    - data/raw/tips.csv
    - data/processed/train_tips.csv
    - data/processed/test_tips.csv


