base:
  project: tips-project
  random_state: 42
  target_col: 'total_bill'

data_source:
  s3_source: data_given/tips.csv

load_data:
  raw_dataset_csv: data/raw/tips.csv

split_data:
  train_path: data/processed/train_tips.csv
  test_path: data/processed/test_tips.csv
  test_size: 0.2

estimators:
  ElasticNet:
    params:
      # alpha: 0.88
      # l1_ratio: 0.89
      alpha: 0.002
      l1_ratio: 0.02
model_dir: saved_models

reports:
  params: reports/params.json
  scores: reports/scores.json

webapp_model_dir: prediction_service/model/model.joblib